# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'installer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from genericpath import exists
import os 
from shutil import copyfile
import win32com.client
import winshell


class Ui_VImage(object):

    def setupUi(self, VImage):

        self.path = "/VMediaPlayer"
        VImage.setObjectName("VImage")
        VImage.resize(493, 427)
        VImage.setStyleSheet("#VImage{\n"
"    background:rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    background:rgb(250,50,0);\n"
"font: 16pt \"Impact\";\n"
"border-radius:15px;\n"
"color:white;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background:rgb(250,100,0);\n"
"font: 16pt \"Impact\";\n"
"border-radius:15px;\n"
"color:white;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background:rgb(200,150, 0);\n"
"font: 16pt \"Impact\";\n"
"border-radius:15px;\n"
"color:white;\n"
"}")
        VImage.setWindowIcon(QtGui.QIcon("vmediaplayer.png"))
        self.pushButton = QtWidgets.QPushButton(VImage)
        self.pushButton.setGeometry(QtCore.QRect(160, 340, 171, 51))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(VImage)
        self.progressBar.setGeometry(QtCore.QRect(80, 190, 351, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(VImage)
        self.label.setGeometry(QtCore.QRect(160, 10, 221, 71))
        self.label.setStyleSheet("font: 16pt \"Impact\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(VImage)
        self.label_2.setGeometry(QtCore.QRect(80, 155, 311, 21))
        self.label_2.setStyleSheet("font:10pt;")
        self.label_2.setObjectName("label_2")
        self.pushButton.clicked.connect(self.Install)
        self.retranslateUi(VImage)
        QtCore.QMetaObject.connectSlotsByName(VImage)

    def retranslateUi(self, VImage):
        _translate = QtCore.QCoreApplication.translate
        VImage.setWindowTitle(_translate("VImage", "VMediaPlayer Installer"))
        self.pushButton.setText(_translate("VImage", "Install"))
        self.label.setText(_translate("VImage", "VMP Installer"))
        self.label_2.setText(_translate("VImage", "Filename"))

    def Install(self):
        if not exists(self.path):
            os.mkdir(self.path)

        self.label_2.setText("Installing: backward.png")
        copyfile("rotate_flip_icon.png", self.path + "/backward.png")
        self.label_2.setText("Installing: forward.png")
        copyfile("rotate_flip_icon.png", self.path + "/forward.png")
        self.label_2.setText("Installing: mute.png")
        copyfile("rotate_flip_icon.png", self.path + "/mute.png")
        self.progressBar.setValue(25)
        self.label_2.setText("Installing pause.png")
        copyfile("rotate_right_icon.png", self.path + "/pause.png")
        self.progressBar.setValue(50)
        self.label_2.setText("Installing play.png")
        copyfile("rotate_left_icon.png", self.path + "/play.png")
        self.progressBar.setValue(75)
        self.label_2.setText("Installing VMediaPlayer.exe")
        copyfile("VMediaPlayer", self.path + "/VMediaPlayer.exe")
        self.progressBar.setValue(100)
        self.Create_Shortcut()
        self.label.setText("VMP Installed!")
        self.label_2.setText("VMP Installed!")
        self.pushButton.setDisabled(True)

    def Create_Shortcut(self):
        desktop = winshell.desktop() 
        disk = desktop[:1]
        path = os.path.join(desktop, "VMediaPlayer.lnk")
        target = disk + ":\\VMediaPlayer\\VMediaPlayer.exe"
        shell = win32com.client.Dispatch("WScript.Shell")
        shortcut = shell.CreateShortCut(path)
        shortcut.Targetpath = target
        shortcut.WindowStyle = 7 
        shortcut.save()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VImage = QtWidgets.QWidget()
    ui = Ui_VImage()
    ui.setupUi(VImage)
    VImage.show()
    sys.exit(app.exec_())
